
import type { Metadata } from 'next';
import { Inter } from 'next/font/google'; // Keep Inter font
import './globals.css';
import { Toaster } from "@/components/ui/toaster"; // Import Toaster

// Initialize Inter font with subsets
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  // Updated title and description
  title: 'PoemPic - AI Shayari Generator from Photos',
  description: 'Upload an image and get a unique Hindi shayari generated by AI based on its content and mood.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Add suppressHydrationWarning to handle browser extension attribute mismatches */}
      <body className={`${inter.className} antialiased`} suppressHydrationWarning={true}>
        {children}
        <Toaster /> {/* Add Toaster component */}
      </body>
    </html>
  );
}
